<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinEXE</OutputType> <!-- Remember to change this -->
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <ApplicationIcon>Assets\Icons\App General\Speck App Icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.11" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.11" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.11" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.11" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.11">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Fonts.Avalonia.JetBrainsMono" Version="0.14.0" />
    <PackageReference Include="LM-Kit.NET" Version="2026.2.2" />
    <PackageReference Include="MessageBox.Avalonia" Version="3.3.1.1" />
    <PackageReference Include="Svg.Controls.Skia.Avalonia" Version="11.3.9.2" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="MainSpeck.axaml.cs">
      <DependentUpon>MainSpeck.axaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Assets\Icons\Menu Items\MenuToggleButton.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Scanners\Nuclei\nuclei.exe" />
    <None Remove="Scanners\Osquery\osqueryi.exe" />
    <None Remove="Scanners\Trivy\trivy.exe" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Scanners\Nuclei\nuclei.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Scanners\Osquery\osqueryi.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Scanners\Trivy\trivy.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\Icons\App General\Speck App Icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\Icons\Scan Items\" />
    <Folder Include="Assets\Specks\" />
  </ItemGroup>
</Project>
